name: Help64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.help64.Help64
api-version: 1.17
depend: []
commands:
  zzz:
    description: Main command for Help64
  sellhead:
    description: Command for sellhead